# Generated by Django 5.0.6 on 2024-06-28 01:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("users_products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="owner",
            field=models.ManyToManyField(
                related_name="my_products",
                through="users_products.UserProduct",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
